language: go
go:
- tip
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
script:
- ./test-coverage.sh
install:
- go get github.com/thoj/go-ircevent
- go get github.com/smartystreets/goconvey/convey
notifications:
  irc: chat.freenode.net#go-bot
env:
  global:
    secure: nkti8neGgka7bslEGqXlZBZLhPS6G1KJFQFO+z6N5GXzd8OWsNxzgcZWTFA0sScd7ntI98C02oTwVRkZhXoOl7xqyLktWrnfJFZLHmmMHibuzuYNMuXRsOEI1LP0QHxzWkMBrpWZP3M6yzLn9gAFlbo0X3ZXHCxqGsORseFEInQ=
